name: Build and Test React Application

# controle
on:
  # Trigger the workflow on push or pull request events to the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# jobs
jobs:
  build_test:
    runs-on: ubuntu-latest

    # steps
    steps:
      # checkout the repository
      - uses: actions/checkout@v3

      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: npm ci, build and test
        run: |
          npm ci
          npm run build --if-present
          npm test

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3

      - name: Upload artifact for deployment
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload build folder
          path: build

  # deploy to github pages
  deploy:
    needs: build_test
    runs-on: ubuntu-latest

    # Grant GITHUB_TOKEN permissions to deploy to GitHub Pages
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3

         

